pipeline
{
  agent any
  {
     stages
     {
      stage('check maven version')
      {
          steps
          {
           bat 'mvn -v'
           
           }
      }
      
     
     }
   }
 }
